### PR TITLE
ci: automated jira issue creation workflow

### PR DESCRIPTION
**Pull request by jooohhn**
### Summary

Sets up automated jira tickets creation for new issues to help triage system.

### CODE REVIEW

**Review by kelsonpw — APPROVED** [review]

**Comment by kelsonpw** [comment]
Nice! Thanks John!

**Comment by kelsonpw** [comment]
@jooohhn We've been getting a significant amount of issues filed that are just related to not following the installing steps correctly.  Do we care about creating a jira ticket for tickets that don't require any work other than commenting?  Is it possible to change this action to only occour when a certain label is added?

**Comment by jooohhn** [comment]
@kelsonpw SDK has a weekly oncall person, for simple tickets they'll close them out. I think because we prefer the oncall closing easier tickets rather than letting an important one slip unnonticed

**Comment by kelsonpw** [comment]
@jooohhn makes sense, this is good to go!

**Pull request merged**
