### PR TITLE
ci: add npm exclusion list

### PR DESCRIPTION
**Pull request by yuhao900914**
Screen Shot 2021-03-24 at 10 38 02 AM
The attachment shows the folder tree when install the fork npm on an example RN app.

### CODE REVIEW

**Comment by kelsonpw** [comment]
What do you mean by fork npm?

**Comment by yuhao900914** [comment]
I fork the Amplitude-RN to my github, do the same edits on the fork repo. Then I release the fork one which is @hao.yu/amplitude-react-native to npm though github workflow release , and try to install it in a RN app for testing.  That's how I test it.  Or any better way I can test it out?

**Comment by kelsonpw** [comment]
> I fork the Amplitude-RN to my github, do the same edits on the fork repo. Then I release the fork one which is @hao.yu/amplitude-react-native to npm though github workflow release , and try to install it in a RN app for testing. That's how I test it. Or any better way I can test it out?
> @kelsonpw

That works fine 👍.  The only issue is that the project is published to npm with a similar name to this package and shows up higher in search rankings: 
image

I'd ask that you delete the package from NPM and use a different name for publishing that doesn't introduce confusion around which package users should use.

**Comment by yuhao900914** [comment]
> I'd ask that you delete the package from NPM, use a different name for publishing that doesn't introduce confusion around which package users should use, and remove the Official SDK description.

Removed the fork one.

**Review by kelsonpw — APPROVED** [review]

**Pull request merged**
